// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tttreknftkvneyplbmzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0dHJla25mdGt2bmV5cGxibXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTk5MzIsImV4cCI6MjA2OTQ3NTkzMn0.cYfYy-3QA1KNLuvfSQN8td9JoFcpi5aRyjdfWB6h4h4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});